export const faqs = [
  ["Is the valuation free?", "Yes. Gold Table event valuations are free. There is no charge for hearing what we find or for choosing not to sell."],
  ["Do I have to sell?", "No. We explain what we find and any offer we can make. You can accept, ask questions or take every item home."],
  ["What items can I bring?", "Gold and silver jewellery, broken pieces, coins, bullion, watches and inherited collections are welcome. We cannot promise that every item will be suitable for purchase."],
  ["Can I bring broken jewellery?", "Yes. Broken chains, single earrings and damaged or unfashionable pieces may still contain precious metal."],
  ["How long does a valuation take?", "Most event appointments are planned in 15-minute intervals. Larger collections may take longer."],
  ["How do you test the gold?", "The valuer may inspect hallmarks, weigh items and use appropriate testing methods where needed. They will explain what they are doing and what they find."],
  ["How do you calculate the value?", "The offer considers metal content, weight, condition, possible resale value and the relevant market price. We explain the basis before you decide."],
  ["How and when will I be paid if I sell?", "The available payment method and timing will be explained before you agree to a sale. Check your event confirmation for any payment information you need to bring."],
  ["What identification do I need?", "If identification is required to complete a sale, your event confirmation will explain what to bring. You can still attend for a valuation if you are not ready to sell."],
  ["Can I attend without an appointment?", "Some events welcome walk-ins. Check the individual event page for the visit options."],
  ["Can I bring several items?", "Yes. Bring as many as you can comfortably carry, but a larger collection may need extra time."],
  ["Do you buy silver or watches?", "We can assess many silver items and watches, though not every item will be suitable for purchase."],
  ["What happens if I do not accept the offer?", "You simply take your items home. There is no charge and no pressure to sell."],
  ["Are valuations private?", "Events are planned so valuations and conversations can be handled as discreetly as the venue setup allows."],
  ["Can I mail my items instead?", "The mail-in service is not currently available. Please use the event finder to see published local dates."],
  ["How can my venue host an event?", "Use the short venue form to share your venue name, postcode and contact details. The first step is a simple fit check before practical arrangements are discussed."],
] as const;
